import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Alumni_Sans, Rubik } from "next/font/google";

const alumniSans = Alumni_Sans({
  subsets: ["latin"],
  weight: "100",
  variable: "--font-alumni-sans",
});

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

const metadata: Metadata = {
  title: "Forrest's Digital Abode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${alumniSans.variable} ${rubik.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
